name: tide_ui
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: any
  uuid: ^2.0.2
  vector_math: ">=2.0.6 <3.0.0"
  meta: ">=1.1.2 <2.0.0"
  path_parsing: ^0.1.4
  xml: ^3.5.0
  tide_chart: 
    git:
      url: https://github.com/mechadojo/tidecharts.git
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
      
flutter:
  uses-material-design: true

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400
    - family: FontAwesomeBrands
      fonts:
        - asset: fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: fonts/fa-solid-900.ttf
          weight: 900
