import "dart:io";

Map<String, String> icons = {};

void main(List<String> arguments) {
  var file = File(arguments.first);

  if (!file.existsSync()) {
    print('Cannot find the file "${arguments.first}".');
  }

  var group = "";
  var lines = file.readAsLinesSync();

  for (var line in lines) {
    line = line.trim();
    if (line.startsWith("#")) {
      group = line.substring(1).trim();

      continue;
    }

    if (line.isEmpty) continue;

    var start = line.indexOf('": [');
    var name = line.substring(0, start).substring(1).trim();

    if (icons.containsKey(name) || group == "brands") {
      var next = "$name-$group";
      print("Renaming $name to $next");
      name = next;
    }
    var partial = line.substring(start + 4).trim();
    partial =
        partial.substring(0, partial.length - (partial.endsWith(',') ? 2 : 1));
    partial = partial.replaceAll("[], ", "");
    partial = partial.replaceAll('["Font Awesome"]', "");
    partial = partial.replaceAll(", , ", ", ");

    var codeStart = partial.indexOf(', "');
    var codeEnd = partial.indexOf(', "', codeStart + 3);

    partial = partial.substring(0, codeStart) + partial.substring(codeEnd);
    partial = 'VectorIcon.named("$name",$partial)';
    icons[name] = partial;
  }

  var outfile = "vector_output.txt";

  print("Writing $outfile");

  List<String> generatedOutput = [
    '',
    " import 'vector_icons.dart';"
        '',
    '// THIS FILE IS AUTOMATICALLY GENERATED!',
    '',
    '// File generated using generate_vector_icons.dart.',
    '',
    'Map<String, VectorIcon> iconDefinitions = {',
    '',
  ];

  var keys = icons.keys.toList();
  keys.sort();
  for (var key in keys) {
    generatedOutput.add('"$key":${icons[key]},');
  }

  generatedOutput.addAll(['', '};']);

  File output = File(outfile);
  output.writeAsStringSync(generatedOutput.join('\n'));
}
